### ISSUE TITLE
The Whale Problem

### ISSUE THREAD

**Issue by wwarby** [NoMagicVideos/NoMagicYouTube#1]
Apologies for the unorthodox method of contact (couldn't bring myself to become a YouTube commenter, and couldn't find any other contact details for you). After quite a lot of thinking about the whale problem in your recent video, I've convinced myself that the conclusion you drew from it is wrong. Since I'm not a trained statistician and you clearly are, I'd love to hear why my interpretation of the problem is wrong.

You have two whales and you know that at least one of them is a male whale who was born on a Tuesday. Okay. The question you asked is "What is the probability that they are both male whales?". I think the question you then proceeded to answer is "What is the probability that they are both male whales, at least one of which was born on a Tuesday?", which is a different question with a different probability.

You seem to have smuggled in the irrelevant extra information that you happened to know about one of the whales and made it part of the question itself, which leads to the absurd conclusion that anything else you happen to know which has no bearing on the question being asked can change the probability outcome of the question. For example I could know that one whale weighs 2000lbs, or that it ate sardines for breakfast last week or that there is an orange fishing boat near one of the whales. Would any of this information have any bearing on the outcome of the question you asked? I say no.

I'd further suggest that an additional fact about the birthday is no more or less relevant simply because it happens to be about one of the whales in question. You could substitute your premise "Suppose you have two whales, and you know that at least one of them is male, and there is a seahorse named Fred". You should no more consider the whale's birthday to be relevant when answering the question than you should the seahorse's name. They are both equally irrelevant facts that should be discarded before you start to answer the question, because neither fact does anything to narrow or expand the permutations relevant to the question you asked.

In the video, as soon as you expand the permutations to from 4 to 196 to incorporate the days of the week, you have allowed the irrelevant information you have to insert itself into the question without justification. All the permutations in which neither whale was born on a Tuesday but in which both whales are male still remain permutations that satisfy the outcome of the original question (exactly one third of them).

Whether or not I've convinced you, I hope you'll consider doing a followup video - it was a fun math problem to consider, thanks for posting it ;)

- William (England)

PS. Feel free to delete this from your Github issue log if you like!

**Comment by samrjack** [comment]
Hello @wwarby, I read through your discussion above and I do think it has flaws in it. Since there isn't other feedback I figured I'd throw in some feedback :). I'm also not a statistician but what is life without thinking about whales? I'll start with the statements above that I think have issues then try to give a different way to mentally reason about the outcomes that are given.

So to begin with, you say that he smuggled some irrelevant information into the question by specifying which day of the week the whale was born on, but that is presupposing the conclusion that the information about the day IS irrelevant (which the video is specifically showing that it is not). Then you go on to say later that "All the permutations in which neither whale was born on a Tuesday but in which both whales are male still remain permutations that satisfy the outcome of the original question" (which, by original question, I presume you mean the one that has birthday data, and not the one excluding it, since that's what's in discussion), but that is not true at all since by definition having a whale born on Monday and one born on Friday does not match the premise that we already KNOW that one of the whales is born on a Tuesday.

The thing that makes the question hard is that we fundamentally assume their birthday is irrelevant even though the question is specifically saying that it does matter. If we change it to a detail that FEELS more relevant, then perhaps it will be easier to see the relevance. Lets say that there are 2 different species (that are equally likely) of whale and each species can be male or female. Then I can ask "I saw two separate whales today. One of them was a male from species A. What is the probability that the other whale was a male of either species?" For me, I find that my brain grabs this detail as more meaningful when engaging with the question. Then thinking it through, it makes sense to me that since we don't know whether it was the first whale or second whale that was seen to be a male from species A, then we have to go through the possibilities in a probability square which shows us that it's slightly less likely for both whales to be male (3/7).

What these two setups have in common is that the extra data makes the described whale (and categories of whales that we're considering) more specific. The more detail you have about the whale, the closer the probability gets to becoming 50%. If, for example, you know that the described male whale really does weigh 2000 lbs, then you're looking at a nearly 50% split since it is highly unlikely that the other whale is a male that weighs 2000lbs too.

Perhaps the above discussion doesn't do much to change your mind either, but it is the thought process I when through to reason to myself about what was going on. I hope it helps give a new perspective for you too!

**Comment by wwarby** [comment]
Hi @samrjack, thanks for taking the time to critique my reasoning - I don't think you've persuaded me, so let me see if my response here does anything to your intuitions.

You say that I am presupposing the conclusion that the information about the day IS irrelevant, and that is true. However, I would argue that whatever else the video says about the relevance of the first whale's birthday, you have to focus on the actual question being asked, which is:

![image](https://user-images.githubusercontent.com/6769065/141786546-eaa48e98-9bef-454a-a92a-8d28e9303963.png)

As you can see, the actual question is "What is the probability that they are both male whales?". I'm arguing that any information you happen to have which does not pertain to that specific question must be discarded before you calculate the probability. Consider this thought experiment:

Suppose I have two plastic toy whales which I am holding behind my back. Each one has Male or Female written on the front and the day of the week on which it was born written on the back. Suppose I show you the front of one of plastic whale A (but not the back) and you see that it reads "Male" and I ask you "What is the probability that they are both male whales?". You should answer 1/3. I know what day of the week s written on the back of whale A but you don't, so you can't use that information to inform your probability calculation.

Now, without changing anything else, I turn whale A around and show you that it has Tuesday written on it's back, and I ask you the same question again, "What is the probability that they are both male whales?". Do you have any new information that should cause you to adjust your calculation of probability? No. If you disagree with this conclusion, then I think you must also concede that if the whale had a red eye or a scratch on it's back or I was holding up three fingers whilst I turned the plastic whale around in my hand, all of these facts would meet the same threshold of new information as the birthday, and if any of these facts should influence the probability then all of them should. By contrast I say they are all irrelevant and they can all be discarded. The question being asked (again, "What is the probability that they are both male whales?") doesn't acquire new conditions simply because you have additional irrelevant information available to you.

Let's look at your other example: "I saw two separate whales today. One of them was a male from species A. What is the probability that the other whale was a male of either species?". To me, this has the same logical fallacy built into it - the correct answer is still 1/3, but it's a little more explicit in this case. Here, you've quite explicitly discarded the relevance of species in the question itself by ending the question with "either species".

In the end I think this comes down to a subjective judgement about what you choose to do with the extra information you have about the first whale. You can (as you have done, and as is done in the video) add the extra information into the possibility square and discard the possibilities that don't match your extra information. I can see why it is tempting to do this. You have the information, so it feels intuitively that to discard it it somehow cheating. But I would argue the problem with doing this is two fold: (a) the consequence of this approach in the real world is to allow any and all irrelevant facts (in effect the totality of human knowledge) to explode the permutations when calculating a probability, and (b) it materially changes the question being asked. In your example, I think the question that has the answer 3/7 is "What is the probability that one whale was a male of species A and the other was a male of either species" and not "What is the probability that the other whale was a male of either species".

Alternatively you can (as I have done) discard irrelevant information before you start the calculation. Intuitively, this feels mathematically correct to me, in a similar way in which matched variables can be discarded in algebra, as in discarding the 4s in `(8+4) - (6-4)` and simplifying to `8 - 6`. I'd argue that this is what we do in the real world when assessing probability. Let me try one more thought experiment which really clarifies things in my head:

Imagine a casino game in which you are dealt two cards. To win, you need be dealt two sixes (the suit doesn't matter). You get to look at the first card you are dealt and change your bet before you are dealt the second card. Let's suppose you turn over just the corner of the first card you are dealt and see that it is a six, but you don't see which suit. After that first card is dealt, what is the probability you will be dealt two sixes? 3/51 I believe. You mentally adjust your bet accordingly. Now, before you put your money down, you lift up the first card you were dealt fully and see that it is the six of diamonds. Do you have any reason to readjust your bet? No, you don't.

**Comment by NoMagicVideos** [comment]
Hi @wwarby, thanks for asking! Let me just start off by saying that I had the same urge to remove this "irrelevant information". After all, in probability, some things are considered to be independent, and the day of the week seems to be completely irrelevant to whether a whale is male or female. And of course, this is the case. If I ask _what is the probability that a whale is male given it is born on a Tuesday?_, the answer is 1/2, just as if I had asked _what is the probability that a whale is male?_. 

Let's dive into this for a second; why are these considered to be independent at all? See, in probability, information helps you narrow in on a result, but if it doesn't help you narrow it down in any meaningful way that changes your initial understanding of the probability. Suppose (just so we have something concrete), we have 1,000,000 whales on the planet. If I say, _I'm thinking of a random whale, guess which one_, you'd have a 1 in a million chance of guessing correctly. If I say then, _oh by the way, the whale is born on a Tuesday_, then you can eliminate 6/7 of those whales, and your probability of guessing correctly goes to 1 in only ~143,000. The number of "correct whales" hasn't changed (it has stayed at 1), but the set of whales we're looking at has changed (from 1,000,000 to 1/7th of that, 1/143,000). 

On the other hand, if I had asked you _I'm thinking of a random whale, guess if it's male_, you would have a 500,000 in a 1,000,000 chance of getting this correct. Now, if I give you more information, saying that the whale was born on a Tuesday, you can still eliminate ~857,000 choices of whales! Seems like a huge improvement, but at the same time, you eliminated 6/7ths of those 500,000 male whales as well.... So your probability is now ~71.5k/143,000... exactly the same as before. 

**See, when we take the same proportion from the top and the bottom (1/7), we can cancel these out entirely, showing "independence".** In a sense, the probability "1 in 2" can be interpreted in two different ways. It can be "there are two scenarios, exactly 1 meets the criteria" or "in every single possible scenario, exactly half of them match the criteria". The former is a simplification, both in an arithmetic sense and in a language sense. Of course there are more than 2 whales in the world, and of course there are more than 1 male whales in the world. 

We can even be more extreme. _What is the probability that this coin is heads given I win a Pulitzer_. This is a silly premise. The odds that I win a Pulitzer is 1 in a billion, a trillion, whatever. Nevertheless, this is information! I am now only looking at the possible worlds where I have won a Pulitzer! In the infinite set of all possible worlds that you can imagine, I have now eliminated 99.999999% (or however many more nines) of them, and am now only looking at worlds where I have won a Pulitzer. Of the remaining 0.000001% (or however many zeroes) worlds left, unfortunately for me, still, exactly half of the times the coin lands heads and half of the time the coin lands tails. Why? Because in eliminating those 99.9 worlds, exactly half of them the coin landed on heads, and half landed on tails. I'll restate: **it's the _proportion_ of worlds we look at that matters**. 

Now that we got that out of the way, let's address some of your points. 

**We've inserted Irrelevant Information to the Problem**
Irrelevant? In what sense? If I won a Pulitzer, it would certainly be relevant to me. And certainly, the world would probably look a bit weirder than the one we live in now. Sure, being born on a Tuesday isn't as rare or interesting as a Pulitzer, but it still tells us something about the whale and the world we live in. 

Perhaps by irrelevant, we mean that it is irrelevant to the probability calculation. That certainly is the case for my Pulitzer/coin flipping example; those things don't seem to affect each others' probabilities at all. But there's a bit of circular logic here: It is irrelevant because it doesn't affect the probability, and it doesn't affect the probability because it is irrelevant. I think the first statement makes sense to me, _something that is relevant shouldn't affect the probability_. The second statement on the other hand, begs the question on how we determine irrelevancy. Sure! I added the information to the diagram of 196 worlds without justification. But if were truly irrelevant, I wouldn't be able to make that animation where the answer turns out to be 13/27 instead of 1/3. 

Same goes for sardines or orange fishing boats! If it is truly irrelevant information, then we can list out our "possible worlds" all the live long day, we should still be able to eliminate _proportionally_ the set of total worlds and the set of worlds that our criteria remains true (in this case, that both whales are male). When we drew those diagrams out however, this turned out not to be the case. 

**And then there's a seahorse named Fred**
Ahh, sounds similar to my Pulitzer/coin flip story. So why is Fred "less significant" than "one of the whales is male born on a Tuesday"? The simple and non-answer is: "it's just different". I mean, if you draw out the diagrams, but this time with a third entity, a seahorse with a name that can be anything (Fred, John, whatever), you'd still be able to eliminate the same proportion of worlds from the set of all possible worlds as you would from the set of worlds where one of the whales is a male born on a Tuesday. You can try it, I wouldn't recommend it because there's a lot of different possible names for a Seahorse and drawing those out seems to be quite difficult, but if you managed to do the work, you would find that with or without Fred, the probability stays the same. 

The more complicated answer (which I touch upon a little in the video), is that we're talking about two combination of whales, and the fact that one of them was born on a Tuesday changes the proportion in which we eliminate our worlds and criteria worlds. 

The simplest answer that helped me sorta intuit this? 
![image](https://user-images.githubusercontent.com/88295556/142233395-4265ac85-50b0-4008-be8f-aac55f280a1d.png)
The whale highlighted in green (both males are whales born on a Tuesday). It has a 1 in 196 chance of being in that scenario (1/14 * 1/14), and 1/49 of those cases where both whales are male (1/7 * 1/7). When "counting" the possibilities, we count 1/7th for the first whale being born on a Tuesday (blue), 1/7th for the second whale being born on a Tuesday (red), and subtract 1/49 to avoid double counting (green). Notice that as you make this item rarer, (suppose instead of being born on a Tuesday, they're born on the 14th of January), the 1/7 becomes 1/365, approximately 50 times rarer, but the intersection becomes 365 times rarer, to 1/365^2 instead of 1/7^2. This change in proportion cascades throughout to ultimately affect the final probability. A shortened explanation, you are free to play around with the math yourself of course. 

I guess if there was one sentence to take away, irrelevant information is irrelevant because it doesn't affect the probability, so if it were truly irrelevant, making all these diagrams shouldn't lead to a different result. Since it does, the information seems to be relevant. 

Thanks for watching and reading! Hope this helps, if not convince you of the problem, then at least provide a little bit of insight :)
